### ISSUE TITLE
Multiple publish processor per Store

### ISSUE THREAD

**Issue by danielceinos** [bq/mini-kotlin#4]
Calling to `flowable` store's extension create a new `PublishProcessor` each time. 

Shouldn't the extension provide an unique instance for each Store?

This is a big problem on doing one shots operations, despite of `takeUntil` Rx`s operator store keep hold each listener.

**Comment by danielceinos** [comment]
We investigated this and we saw that changing calling `doOnTerminate` never calls but `doFinally` yes on a subscription dispose.

**Comment by adriangl** [comment]
Hey @danielceinos 
I fixed this in #5, feel free to check the PR and suggest any changes ;)

**Comment by adriangl** [comment]
The PR is still not merged, so please, leave the issue open until the PR is closed ;)
