### ISSUE TITLE
Fork or use original minikorp/mini

### ISSUE THREAD

**Issue by pabloogc** [bq/mini-kotlin#6]
It's kind of pointless to bugfix in two places or to have different set of core features specially now that mini 5.0 is stable and coroutines shake it a bit.

This repository is already missing critical features like incremental compilation and copy paste can only get so far (like the bugfix and tests here https://github.com/bq/mini-kotlin/pull/5).

So maybe fork minikorp repo and commit core changes there, keep bq fork for bq specifics changes.

**Comment by danielgallegovico** [comment]
Taking into account that this mini implementation has been backed up by BQ engineers for years and we currently use it on several projects, we cannot afford to use a personal branch like mini 5.0 in our projects.

You are more than welcome to contribute here (like you did in the past). But if you prefer to continue your own evolution, we are glad to share ideas and experiences.

Don't forget it: the important thing here is to build better software ;)
